# .github/workflows/main.yml
name: CI
on:
  push:
    branches: ok
  
# demo
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.21.1'
        env: 
          CI: false
      - name: setup .env
        run: cp /home/ubuntu/runner/_work/lost-and-found/.env /home/ubuntu/runner/_work/lost-and-found/lost-and-found
      - name: Install NPM dependencies
        run: npm install nuxt
      - name: npm Install 
        run: npm install
      - name: Serving Static Files
        run: npm run generate
#      - name: Cleaning the cache
#        run: npm cache clean --force
