# .github/workflows/main.yml
name: CI
on:
  push:
    branches: staging

jobs:
  build:
    runs-on: staging
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.16.0'
      - name: Install NPM dependencies
        run: npm install
      - name: setup .env
        run: cp /home/ubuntu/actions-runner/_work/lost-and-found/.env /home/ubuntu/actions-runner/_work/lost-and-found/lost-and-found
      - name: npm i
        run: npm i
      - name: Generating Build
        run: npm run build
      - name: Serving Static Files
        run: npm run generate
