name: Stage
on:
  push:
    branches:
      - staging
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE_STG }}" > .env
    - uses: actions/setup-node@v2
        with:
          node-version: '14.21.1'
    - name: Create Build
        run: |
          npm install nuxt
          npm install
          npm run generate
        env:
          CI: false
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        path: dist/
        remote_path: ${{ secrets.DEPLOY_PATH_STG }}
        remote_host: ${{ secrets.DEPLOY_HOST_STG }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY_STG }}
